# Generated by Django 4.0.2 on 2022-04-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measurment',
            new_name='Measurement',
        ),
    ]
